name: Deploy to Auth0 production account
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download files from the current repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"
      - name: Install the auth0-deploy-cli
        run: npm install
      - name: Import changes to the Auth0 production account
        env:
          AUTH0_CLIENT_SECRET: ${{ secrets.PROD_AUTH0_CLIENT_SECRET }}
        run: npm run import:prod
