name: Deploy to Fauna staging account
on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download files from the current repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"
      - name: NPM Install
        run: npm install
      - name: Export Fauna Dev DB config
        env:
          DEV_FAUNA_CLI_SECRET: ${{ secrets.DEV_FAUNA_CLI_SECRET }}
        run: npm run exportfauna:dev
      - name: Import Fauna DB config to Staging
        env:
          FAUNA_CLI_SECRET: ${{ secrets.STAGING_FAUNA_CLI_SECRET }}
        run: npm run importfauna:staging
